### ISSUE TITLE
Very low contrast when typing incorrect json

### ISSUE THREAD

**Issue by RichieBzzzt** [soft-aesthetic/soft-era-vs-code#8]
Hello!

Started using this theme today and am really into it, however I have noticed that the contrast is very low for json if it is incorrect (see attached photo: after glossary there is some text typed there, but it's difficult to see what i actually wrong)

![json_formattting_issues](https://user-images.githubusercontent.com/26192003/41669291-5e7a446c-74a9-11e8-87bf-6392bfab1137.PNG)

Of course one remedy for this is for me to be not quite so bad at typing out json.....

Thanks and keep up the good work!

**Comment by khendrikse** [comment]
I had the same issue, I added the following to my settings:

`
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "invalid.illegal",
                "settings": {
                    "foreground": "#e0d3ac"
                }
            }
        ]
    }
`

**Comment by lovemecomputer** [comment]
aaaaaa thank you @khendrikse !!! this issue has been unpredictable for me to reproduce, which makes sense bc i don't edit .json files very guess? i'll put in a fix based on ur code now!

**Comment by lovemecomputer** [comment]
wait… okay this is weird, there is a syntax rule for this in the `.tmTheme` file, set to `#dd698ccc`. i will investigate this matter further!!
